name: Simple Deploy Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test Node.js
        run: |
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -la
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: List dist contents
        run: |
          echo "Dist folder contents:"
          ls -la dist/ 